import type { Candidate, MatchRecord, Membership } from "@/lib/types";

export const mockCandidates: Candidate[] = [
  {
    id: "mock-test-female",
    full_name: "테스트 여성",
    birth_year: 1998,
    gender: "여",
    region: "강북구",
    occupation: "약사",
    work_summary: "이쁨",
    education: "테스트대학교",
    religion: "무교",
    mbti: "ISFJ",
    personality_summary:
      "테스트용으로 항상 노출되는 여성 프로필입니다.",
    ideal_type: "테스트 남성과 매칭 확인",
    notes_private: "대시보드 노출 확인용 데이터",
    status: "active",
    highlight_tags: ["테스트", "강북구", "약사"],
    image_url: "/99년생 여자 기획자.png",
    paired_candidate_id: null,
    created_at: "2026-04-02T09:00:00.000Z",
    created_by_name: "시스템",
  },
  {
    id: "mock-test-male",
    full_name: "테스트 남성",
    birth_year: 1996,
    gender: "남",
    region: "성수동",
    occupation: "개발자",
    work_summary: "훈훈함",
    education: "테스트대학교",
    religion: "무교",
    mbti: "INTJ",
    personality_summary:
      "테스트용으로 항상 노출되는 남성 프로필입니다.",
    ideal_type: "테스트 여성과 흐름 보드 확인",
    notes_private: "타임라인/보드 회귀 확인용 데이터",
    status: "active",
    highlight_tags: ["테스트", "성수동", "개발자"],
    image_url: "/94년생 남자 개발자.png",
    paired_candidate_id: null,
    created_at: "2026-04-02T09:05:00.000Z",
    created_by_name: "시스템",
  },
  {
    id: "cand-1",
    full_name: "김서연",
    birth_year: 1994,
    gender: "여",
    region: "서울",
    occupation: "기획자",
    work_summary: "INNOVATE · 서비스 기획",
    education: "연세대학교",
    religion: "무교",
    mbti: "ENFJ",
    personality_summary:
      "차분하고 센스가 있으며, 대화 흐름을 편하게 만들고 상대를 세심하게 배려하는 타입.",
    ideal_type: "성실하고 유머가 있으며 가족관계가 안정적인 사람.",
    notes_private: "주말에는 전시와 러닝을 즐김. 비흡연 선호.",
    status: "active",
    highlight_tags: ["대화잘함", "서울거주", "비흡연 선호"],
    image_url: "/99년생 여자 기획자.png",
    paired_candidate_id: null,
    created_at: "2026-03-20T09:00:00.000Z",
    created_by_name: "관리자",
  },
  {
    id: "cand-2",
    full_name: "박도윤",
    birth_year: 1991,
    gender: "남",
    region: "판교",
    occupation: "개발자",
    work_summary: "INNOVATE · 백엔드 개발",
    education: "고려대학교",
    religion: "기독교",
    mbti: "ISTJ",
    personality_summary:
      "유쾌하면서도 성실하고 생활 감각이 좋아, 신뢰감 있는 관계를 차분하게 쌓아가는 스타일.",
    ideal_type: "생활 루틴이 맞고 따뜻한 대화를 오래 이어갈 수 있는 사람.",
    notes_private: "운동 꾸준히 함. 결혼 의지가 분명함.",
    status: "active",
    highlight_tags: ["결혼의지 높음", "판교", "운동습관"],
    image_url: "/94년생 남자 개발자.png",
    paired_candidate_id: null,
    created_at: "2026-02-18T09:00:00.000Z",
    created_by_name: "관리자",
  },
];

export const mockMatchRecords: MatchRecord[] = [
  {
    id: "match-test-1",
    candidate_id: "mock-test-male",
    counterpart_label: "테스트 여성",
    counterpart_candidate_id: "mock-test-female",
    matchmaker_name: "시스템",
    outcome: "intro_sent",
    summary: "테스트 남성과 테스트 여성의 매칭 진행을 시작했습니다.",
    happened_on: "2026-04-02",
  },
  {
    id: "match-1",
    candidate_id: "cand-1",
    counterpart_label: "1991년생 판교 개발자",
    counterpart_candidate_id: "cand-2",
    matchmaker_name: "준성",
    outcome: "first_meeting",
    summary: "첫 식사 이후 한 번 더 보기로 했고 대화 흐름이 좋았음.",
    happened_on: "2026-03-26",
  },
];

export const mockMemberships: Membership[] = [
  {
    user_id: "user-1",
    username: "junseong",
    full_name: "준성 김",
    role: "super_admin",
    status: "approved",
    approved_by: null,
    created_at: "2026-03-15T00:00:00.000Z",
  },
];
