import type { Candidate } from "@/lib/types";

export const previewSceneCandidates: Candidate[] = [
  {
    id: "preview-left",
    full_name: "여성 프로필",
    birth_year: 1997,
    gender: "여",
    region: "서울",
    occupation: "브랜드 기획",
    work_summary: "프리뷰",
    education: "",
    religion: "",
    mbti: null,
    personality_summary: "랜딩 화면 프리뷰용 카드입니다.",
    ideal_type: "",
    notes_private: "",
    status: "active",
    highlight_tags: [],
    image_url: null,
    paired_candidate_id: null,
    created_at: "2026-04-02T00:00:00.000Z",
    created_by_name: "system",
  },
  {
    id: "preview-right",
    full_name: "남성 프로필",
    birth_year: 1995,
    gender: "남",
    region: "수도권",
    occupation: "프로덕트",
    work_summary: "프리뷰",
    education: "",
    religion: "",
    mbti: null,
    personality_summary: "랜딩 화면 프리뷰용 카드입니다.",
    ideal_type: "",
    notes_private: "",
    status: "active",
    highlight_tags: [],
    image_url: null,
    paired_candidate_id: null,
    created_at: "2026-04-02T00:00:01.000Z",
    created_by_name: "system",
  },
];
